### ISSUE TITLE
No ID does not make ID ¯\_(ツ)_/¯

### ISSUE THREAD

**Issue by fourk0** [lucagez/Debucsser#9]
When there isn’t an ID “id = ¯\_(ツ) _/¯” shouldn’t show up. 
It should look like this: 
Class = “title”
293 × 1024
And vice-versa.
In my opinion that would make it look a lot better.
And if you actually have an ID or class called ¯\ _(ツ) _/¯ you would get confused.

**Comment by pitust** [comment]
Have fix for demo: [demo](https://codepen.io/Piott/pen/pGNqWZ)

**Comment by pitust** [comment]
It's hard-coded at line 103:
`        <h2>id: <strong>${id || `¯\\_(ツ)_/¯`}</strong></h2>`
classes have the same thing

**Comment by pitust** [comment]
I think @lucagez made this on purpose
